#!/usr/bin/env bash

PLUGIN_PATH="$(dirname "${BASH_SOURCE[0]}")"

PLUGIN_NAME="$(basename $PLUGIN_PATH)"

SUPPORT_PATH="${PLUGIN_PATH/$PLUGIN_NAME/support}"

SUPPORT_PLUGIN="${SUPPORT_PATH}/plugin"

source $SUPPORT_PLUGIN

function plugin_brew_load() {

  eval "brew --version" > /dev/null

  if [[ $? -ne 0 ]]; then
    return $ERROR_NOT_FOUND
  fi

  return 0
}

function plugin_apt_add() {

  local input=$(plugin_read_dependency)

  eval "declare -A params"=${input#*=}

  brew install ${params[Package]}
}

function plugin_apt_remove() {
  local input=$(plugin_read_dependency)

  eval "declare -A params"=${input#*=}

  brew uninstall ${params[Package]}
}

declare -A plugin=(
  [OnLoad]=plugin_brew_load
  [OnAdd]=plugin_brew_add
  [OnRemove]=plugin_brew_remove
)

plugin_execute "$(declare -p plugin)"


