#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Resolver with which file?"
  exit -1
fi

FILE_URI=$1

if [ -f "$FILE_URI" ]; then
  FILE_URI=$(readlink -f $FILE_URI)
fi

TEMP_DIR=${2:-"$(mktemp -u)"}

echo "RESOLVE"
echo "$TEMP_DIR"
echo "$FILE_URI"
echo "VAR1=VAL1"
echo "END"

